[default]
address = "0.0.0.0"
port = 8520
workers = 16
max_blocking = 512
keep_alive = 5
log_level = "normal"

key = "abc"
data_path = "./tests/data"

[[default.rr_config]]
name = "files"
path = "./tests/files"

[[default.rr_config]]
name = "files1"
path = "./tests/files1"
